---

- name: greeting
  shell: echo "Hello World!"

- name: whoami
  shell: whoami

- name: whoami (become)
  shell: whoami
  become: yes

- name: test sudo
  file:
    path: /root/test
    owner: root
    group: root
    state: touch
  become: yes
